/* ============================================================================
   data.js  —  Seed catalogs for MacroMax
   These are the built-in defaults. The user's own custom foods / exercises /
   splits are stored separately in localStorage and merged on top of these.
   Macros are per 100 g (or per 100 ml for drinks): kcal, p = protein,
   c = carbs, f = fat (all in grams). `serving` is an optional convenience
   portion so you can log "1 egg" instead of "50 g".
   ========================================================================== */

const SEED_FOODS = [
  // ---- Protein (meat, fish, eggs, plant protein, legumes) ----
  { id: "chicken-breast", name: "Chicken breast (cooked)",  cat: "protein", kcal: 165, p: 31,   c: 0,   f: 3.6, serving: { label: "1 fillet (120 g)", grams: 120 } },
  { id: "chicken-thigh",  name: "Chicken thigh (cooked)",   cat: "protein", kcal: 209, p: 26,   c: 0,   f: 11 },
  { id: "turkey-breast",  name: "Turkey breast (cooked)",   cat: "protein", kcal: 135, p: 30,   c: 0,   f: 1 },
  { id: "ground-turkey",  name: "Ground turkey 93% (cooked)", cat: "protein", kcal: 176, p: 27, c: 0,   f: 7 },
  { id: "beef-mince-5",   name: "Lean beef mince 5% (cooked)", cat: "protein", kcal: 170, p: 26, c: 0,  f: 7 },
  { id: "steak-sirloin",  name: "Sirloin steak (cooked)",   cat: "protein", kcal: 244, p: 27,   c: 0,   f: 15 },
  { id: "pork-chop",      name: "Pork chop (cooked)",       cat: "protein", kcal: 231, p: 26,   c: 0,   f: 14 },
  { id: "lamb",           name: "Lamb (cooked)",            cat: "protein", kcal: 294, p: 25,   c: 0,   f: 21 },
  { id: "ham",            name: "Ham, sliced",              cat: "protein", kcal: 145, p: 21,   c: 1.5, f: 6,  serving: { label: "1 slice (30 g)", grams: 30 } },
  { id: "bacon",          name: "Bacon (cooked)",           cat: "protein", kcal: 541, p: 37,   c: 1.4, f: 42, serving: { label: "1 slice (12 g)", grams: 12 } },
  { id: "salmon",         name: "Salmon (cooked)",          cat: "protein", kcal: 208, p: 20,   c: 0,   f: 13 },
  { id: "tuna-can",       name: "Tuna, canned in water",    cat: "protein", kcal: 116, p: 26,   c: 0,   f: 1,  serving: { label: "1 can (95 g)", grams: 95 } },
  { id: "cod",            name: "Cod (cooked)",             cat: "protein", kcal: 105, p: 23,   c: 0,   f: 0.9 },
  { id: "tilapia",        name: "Tilapia (cooked)",         cat: "protein", kcal: 128, p: 26,   c: 0,   f: 2.7 },
  { id: "shrimp",         name: "Shrimp (cooked)",          cat: "protein", kcal: 99,  p: 24,   c: 0.2, f: 0.3 },
  { id: "sardines",       name: "Sardines, canned",         cat: "protein", kcal: 208, p: 25,   c: 0,   f: 11, serving: { label: "1 can (90 g)", grams: 90 } },
  { id: "egg",            name: "Egg, whole",               cat: "protein", kcal: 143, p: 13,   c: 1.1, f: 9.5, serving: { label: "1 large egg (50 g)", grams: 50 } },
  { id: "egg-white",      name: "Egg white",                cat: "protein", kcal: 52,  p: 11,   c: 0.7, f: 0.2, serving: { label: "1 white (33 g)", grams: 33 } },
  { id: "tofu",           name: "Tofu, firm",               cat: "protein", kcal: 144, p: 17,   c: 3,   f: 9 },
  { id: "tempeh",         name: "Tempeh",                   cat: "protein", kcal: 192, p: 20,   c: 8,   f: 11 },
  { id: "seitan",         name: "Seitan",                   cat: "protein", kcal: 141, p: 25,   c: 4,   f: 2 },
  { id: "edamame",        name: "Edamame (cooked)",         cat: "protein", kcal: 121, p: 12,   c: 9,   f: 5 },
  { id: "lentils",        name: "Lentils (cooked)",         cat: "protein", kcal: 116, p: 9,    c: 20,  f: 0.4 },
  { id: "chickpeas",      name: "Chickpeas (cooked)",       cat: "protein", kcal: 164, p: 9,    c: 27,  f: 2.6 },
  { id: "black-beans",    name: "Black beans (cooked)",     cat: "protein", kcal: 132, p: 9,    c: 24,  f: 0.5 },
  { id: "kidney-beans",   name: "Kidney beans (cooked)",    cat: "protein", kcal: 127, p: 9,    c: 23,  f: 0.5 },
  { id: "whey",           name: "Whey protein powder",      cat: "protein", kcal: 400, p: 80,   c: 8,   f: 6,  serving: { label: "1 scoop (30 g)", grams: 30 } },
  { id: "protein-bar",    name: "Protein bar",              cat: "snack",   kcal: 350, p: 30,   c: 35,  f: 10, serving: { label: "1 bar (60 g)", grams: 60 } },

  // ---- Dairy ----
  { id: "greek-yogurt",   name: "Greek yogurt, 2%",         cat: "dairy",   kcal: 73,  p: 10,   c: 4,   f: 2,  serving: { label: "1 cup (170 g)", grams: 170 } },
  { id: "whole-yogurt",   name: "Yogurt, whole milk plain", cat: "dairy",   kcal: 61,  p: 3.5,  c: 4.7, f: 3.3, serving: { label: "1 cup (170 g)", grams: 170 } },
  { id: "cottage-cheese", name: "Cottage cheese",           cat: "dairy",   kcal: 98,  p: 11,   c: 3.4, f: 4.3 },
  { id: "ricotta",        name: "Ricotta cheese",           cat: "dairy",   kcal: 174, p: 11,   c: 3,   f: 13 },
  { id: "cheddar",        name: "Cheddar cheese",           cat: "dairy",   kcal: 402, p: 25,   c: 1.3, f: 33, serving: { label: "1 slice (30 g)", grams: 30 } },
  { id: "mozzarella",     name: "Mozzarella",               cat: "dairy",   kcal: 280, p: 28,   c: 3,   f: 17, serving: { label: "30 g", grams: 30 } },
  { id: "parmesan",       name: "Parmesan",                 cat: "dairy",   kcal: 431, p: 38,   c: 4,   f: 29, serving: { label: "1 tbsp (10 g)", grams: 10 } },
  { id: "feta",           name: "Feta cheese",              cat: "dairy",   kcal: 264, p: 14,   c: 4,   f: 21, serving: { label: "30 g", grams: 30 } },
  { id: "string-cheese",  name: "String cheese",            cat: "dairy",   kcal: 318, p: 24,   c: 3,   f: 24, serving: { label: "1 stick (28 g)", grams: 28 } },
  { id: "cream-cheese",   name: "Cream cheese",             cat: "dairy",   kcal: 342, p: 6,    c: 4,   f: 34, serving: { label: "1 tbsp (15 g)", grams: 15 } },
  { id: "sour-cream",     name: "Sour cream",               cat: "dairy",   kcal: 198, p: 2.4,  c: 4.6, f: 19, serving: { label: "1 tbsp (15 g)", grams: 15 } },
  { id: "heavy-cream",    name: "Heavy cream",              cat: "dairy",   kcal: 340, p: 2.8,  c: 2.8, f: 36, serving: { label: "1 tbsp (15 g)", grams: 15 } },

  // ---- Carbs / grains ----
  { id: "white-rice",     name: "White rice (cooked)",      cat: "carb",    kcal: 130, p: 2.7,  c: 28,  f: 0.3 },
  { id: "brown-rice",     name: "Brown rice (cooked)",      cat: "carb",    kcal: 123, p: 2.7,  c: 26,  f: 1 },
  { id: "quinoa",         name: "Quinoa (cooked)",          cat: "carb",    kcal: 120, p: 4.4,  c: 21,  f: 1.9 },
  { id: "couscous",       name: "Couscous (cooked)",        cat: "carb",    kcal: 112, p: 3.8,  c: 23,  f: 0.2 },
  { id: "bulgur",         name: "Bulgur (cooked)",          cat: "carb",    kcal: 83,  p: 3,    c: 19,  f: 0.2 },
  { id: "pasta",          name: "Pasta (cooked)",           cat: "carb",    kcal: 157, p: 5.8,  c: 31,  f: 0.9 },
  { id: "gnocchi",        name: "Gnocchi (cooked)",         cat: "carb",    kcal: 130, p: 3,    c: 26,  f: 1.5 },
  { id: "ramen",          name: "Instant ramen noodles",    cat: "carb",    kcal: 436, p: 9,    c: 63,  f: 16, serving: { label: "1 pack (85 g)", grams: 85 } },
  { id: "bread-white",    name: "Bread, white",             cat: "carb",    kcal: 265, p: 9,    c: 49,  f: 3.2, serving: { label: "1 slice (30 g)", grams: 30 } },
  { id: "bread-ww",       name: "Bread, whole wheat",       cat: "carb",    kcal: 247, p: 13,   c: 41,  f: 3.4, serving: { label: "1 slice (30 g)", grams: 30 } },
  { id: "bagel",          name: "Bagel",                    cat: "carb",    kcal: 250, p: 10,   c: 49,  f: 1.5, serving: { label: "1 bagel (100 g)", grams: 100 } },
  { id: "english-muffin", name: "English muffin",           cat: "carb",    kcal: 235, p: 8,    c: 46,  f: 1.8, serving: { label: "1 muffin (57 g)", grams: 57 } },
  { id: "tortilla",       name: "Flour tortilla",           cat: "carb",    kcal: 312, p: 8,    c: 51,  f: 8,  serving: { label: "1 tortilla (50 g)", grams: 50 } },
  { id: "naan",           name: "Naan bread",               cat: "carb",    kcal: 310, p: 9,    c: 50,  f: 8,  serving: { label: "1 naan (90 g)", grams: 90 } },
  { id: "oats",           name: "Oats, dry",                cat: "carb",    kcal: 389, p: 17,   c: 66,  f: 7,  serving: { label: "1 portion (40 g)", grams: 40 } },
  { id: "muesli",         name: "Muesli",                   cat: "carb",    kcal: 362, p: 10,   c: 66,  f: 6,  serving: { label: "1 bowl (50 g)", grams: 50 } },
  { id: "granola",        name: "Granola",                  cat: "carb",    kcal: 471, p: 10,   c: 64,  f: 20, serving: { label: "1 portion (50 g)", grams: 50 } },
  { id: "cornflakes",     name: "Cornflakes",               cat: "carb",    kcal: 357, p: 7,    c: 84,  f: 0.4, serving: { label: "1 bowl (30 g)", grams: 30 } },
  { id: "pancake",        name: "Pancakes",                 cat: "carb",    kcal: 227, p: 6,    c: 28,  f: 10, serving: { label: "1 pancake (40 g)", grams: 40 } },
  { id: "waffle",         name: "Waffle",                   cat: "carb",    kcal: 291, p: 8,    c: 33,  f: 14, serving: { label: "1 waffle (75 g)", grams: 75 } },
  { id: "potato",         name: "Potato (boiled)",          cat: "carb",    kcal: 87,  p: 1.9,  c: 20,  f: 0.1 },
  { id: "sweet-potato",   name: "Sweet potato (baked)",     cat: "carb",    kcal: 90,  p: 2,    c: 21,  f: 0.1 },
  { id: "french-fries",   name: "French fries",             cat: "carb",    kcal: 312, p: 3.4,  c: 41,  f: 15, serving: { label: "medium (117 g)", grams: 117 } },
  { id: "rice-cakes",     name: "Rice cakes",               cat: "snack",   kcal: 387, p: 8,    c: 82,  f: 2.8, serving: { label: "1 cake (9 g)", grams: 9 } },

  // ---- Fruit ----
  { id: "banana",         name: "Banana",                   cat: "fruit",   kcal: 89,  p: 1.1,  c: 23,  f: 0.3, serving: { label: "1 medium (118 g)", grams: 118 } },
  { id: "apple",          name: "Apple",                    cat: "fruit",   kcal: 52,  p: 0.3,  c: 14,  f: 0.2, serving: { label: "1 medium (182 g)", grams: 182 } },
  { id: "pear",           name: "Pear",                     cat: "fruit",   kcal: 57,  p: 0.4,  c: 15,  f: 0.1, serving: { label: "1 medium (178 g)", grams: 178 } },
  { id: "orange",         name: "Orange",                   cat: "fruit",   kcal: 47,  p: 0.9,  c: 12,  f: 0.1, serving: { label: "1 medium (130 g)", grams: 130 } },
  { id: "grapefruit",     name: "Grapefruit",               cat: "fruit",   kcal: 42,  p: 0.8,  c: 11,  f: 0.1, serving: { label: "half (123 g)", grams: 123 } },
  { id: "peach",          name: "Peach",                    cat: "fruit",   kcal: 39,  p: 0.9,  c: 10,  f: 0.3 },
  { id: "kiwi",           name: "Kiwi",                     cat: "fruit",   kcal: 61,  p: 1.1,  c: 15,  f: 0.5, serving: { label: "1 fruit (75 g)", grams: 75 } },
  { id: "grapes",         name: "Grapes",                   cat: "fruit",   kcal: 69,  p: 0.7,  c: 18,  f: 0.2 },
  { id: "pineapple",      name: "Pineapple",                cat: "fruit",   kcal: 50,  p: 0.5,  c: 13,  f: 0.1 },
  { id: "mango",          name: "Mango",                    cat: "fruit",   kcal: 60,  p: 0.8,  c: 15,  f: 0.4 },
  { id: "watermelon",     name: "Watermelon",               cat: "fruit",   kcal: 30,  p: 0.6,  c: 8,   f: 0.2 },
  { id: "blueberries",    name: "Blueberries",              cat: "fruit",   kcal: 57,  p: 0.7,  c: 14,  f: 0.3 },
  { id: "strawberries",   name: "Strawberries",             cat: "fruit",   kcal: 32,  p: 0.7,  c: 7.7, f: 0.3 },
  { id: "raspberries",    name: "Raspberries",              cat: "fruit",   kcal: 52,  p: 1.2,  c: 12,  f: 0.7 },
  { id: "cherries",       name: "Cherries",                 cat: "fruit",   kcal: 63,  p: 1.1,  c: 16,  f: 0.2 },
  { id: "dates",          name: "Dates",                    cat: "fruit",   kcal: 282, p: 2.5,  c: 75,  f: 0.4, serving: { label: "1 date (8 g)", grams: 8 } },
  { id: "raisins",        name: "Raisins",                  cat: "fruit",   kcal: 299, p: 3.1,  c: 79,  f: 0.5, serving: { label: "small box (30 g)", grams: 30 } },

  // ---- Vegetables ----
  { id: "broccoli",       name: "Broccoli (cooked)",        cat: "veg",     kcal: 35,  p: 2.4,  c: 7,   f: 0.4 },
  { id: "cauliflower",    name: "Cauliflower (cooked)",     cat: "veg",     kcal: 23,  p: 1.8,  c: 4,   f: 0.5 },
  { id: "spinach",        name: "Spinach (raw)",            cat: "veg",     kcal: 23,  p: 2.9,  c: 3.6, f: 0.4 },
  { id: "kale",           name: "Kale",                     cat: "veg",     kcal: 35,  p: 2.9,  c: 4.4, f: 1.5 },
  { id: "salad-greens",   name: "Mixed salad greens",       cat: "veg",     kcal: 17,  p: 1.4,  c: 3,   f: 0.2 },
  { id: "carrot",         name: "Carrot",                   cat: "veg",     kcal: 41,  p: 0.9,  c: 10,  f: 0.2, serving: { label: "1 medium (61 g)", grams: 61 } },
  { id: "tomato",         name: "Tomato",                   cat: "veg",     kcal: 18,  p: 0.9,  c: 3.9, f: 0.2, serving: { label: "1 medium (123 g)", grams: 123 } },
  { id: "cucumber",       name: "Cucumber",                 cat: "veg",     kcal: 15,  p: 0.7,  c: 3.6, f: 0.1 },
  { id: "bell-pepper",    name: "Bell pepper",              cat: "veg",     kcal: 31,  p: 1,    c: 6,   f: 0.3 },
  { id: "zucchini",       name: "Zucchini",                 cat: "veg",     kcal: 17,  p: 1.2,  c: 3.1, f: 0.3 },
  { id: "green-beans",    name: "Green beans (cooked)",     cat: "veg",     kcal: 35,  p: 1.9,  c: 8,   f: 0.1 },
  { id: "peas",           name: "Green peas (cooked)",      cat: "veg",     kcal: 84,  p: 5.4,  c: 16,  f: 0.2 },
  { id: "asparagus",      name: "Asparagus (cooked)",       cat: "veg",     kcal: 22,  p: 2.4,  c: 4,   f: 0.2 },
  { id: "mushrooms",      name: "Mushrooms",                cat: "veg",     kcal: 22,  p: 3.1,  c: 3.3, f: 0.3 },
  { id: "corn",           name: "Sweet corn",               cat: "veg",     kcal: 96,  p: 3.4,  c: 21,  f: 1.5 },
  { id: "onion",          name: "Onion",                    cat: "veg",     kcal: 40,  p: 1.1,  c: 9,   f: 0.1 },

  // ---- Fats / nuts / seeds ----
  { id: "avocado",        name: "Avocado",                  cat: "fat",     kcal: 160, p: 2,    c: 9,   f: 15, serving: { label: "half (100 g)", grams: 100 } },
  { id: "almonds",        name: "Almonds",                  cat: "fat",     kcal: 579, p: 21,   c: 22,  f: 50, serving: { label: "1 handful (28 g)", grams: 28 } },
  { id: "walnuts",        name: "Walnuts",                  cat: "fat",     kcal: 654, p: 15,   c: 14,  f: 65, serving: { label: "1 handful (28 g)", grams: 28 } },
  { id: "cashews",        name: "Cashews",                  cat: "fat",     kcal: 553, p: 18,   c: 30,  f: 44, serving: { label: "1 handful (28 g)", grams: 28 } },
  { id: "pistachios",     name: "Pistachios",               cat: "fat",     kcal: 562, p: 20,   c: 28,  f: 45, serving: { label: "1 handful (28 g)", grams: 28 } },
  { id: "peanuts",        name: "Peanuts",                  cat: "fat",     kcal: 567, p: 26,   c: 16,  f: 49, serving: { label: "1 handful (28 g)", grams: 28 } },
  { id: "peanut-butter",  name: "Peanut butter",            cat: "fat",     kcal: 588, p: 25,   c: 20,  f: 50, serving: { label: "2 tbsp (32 g)", grams: 32 } },
  { id: "sunflower-seeds", name: "Sunflower seeds",         cat: "fat",     kcal: 584, p: 21,   c: 20,  f: 51, serving: { label: "1 handful (28 g)", grams: 28 } },
  { id: "chia",           name: "Chia seeds",               cat: "fat",     kcal: 486, p: 17,   c: 42,  f: 31, serving: { label: "1 tbsp (12 g)", grams: 12 } },
  { id: "flax",           name: "Flax seeds",               cat: "fat",     kcal: 534, p: 18,   c: 29,  f: 42, serving: { label: "1 tbsp (10 g)", grams: 10 } },
  { id: "tahini",         name: "Tahini",                   cat: "fat",     kcal: 595, p: 17,   c: 21,  f: 54, serving: { label: "1 tbsp (15 g)", grams: 15 } },
  { id: "hummus",         name: "Hummus",                   cat: "fat",     kcal: 166, p: 7.9,  c: 14,  f: 9.6, serving: { label: "2 tbsp (30 g)", grams: 30 } },
  { id: "olive-oil",      name: "Olive oil",                cat: "fat",     kcal: 884, p: 0,    c: 0,   f: 100, serving: { label: "1 tbsp (14 g)", grams: 14 } },
  { id: "coconut-oil",    name: "Coconut oil",              cat: "fat",     kcal: 862, p: 0,    c: 0,   f: 100, serving: { label: "1 tbsp (14 g)", grams: 14 } },
  { id: "butter",         name: "Butter",                   cat: "fat",     kcal: 717, p: 0.9,  c: 0.1, f: 81, serving: { label: "1 tbsp (14 g)", grams: 14 } },
  { id: "mayo",           name: "Mayonnaise",               cat: "fat",     kcal: 680, p: 1,    c: 0.6, f: 75, serving: { label: "1 tbsp (14 g)", grams: 14 } },

  // ---- Snacks / sweets / spreads ----
  { id: "honey",          name: "Honey",                    cat: "snack",   kcal: 304, p: 0.3,  c: 82,  f: 0,  serving: { label: "1 tbsp (21 g)", grams: 21 } },
  { id: "maple-syrup",    name: "Maple syrup",              cat: "snack",   kcal: 260, p: 0,    c: 67,  f: 0.1, serving: { label: "1 tbsp (20 g)", grams: 20 } },
  { id: "jam",            name: "Jam / preserves",          cat: "snack",   kcal: 278, p: 0.4,  c: 69,  f: 0.1, serving: { label: "1 tbsp (20 g)", grams: 20 } },
  { id: "nutella",        name: "Hazelnut spread (Nutella)", cat: "snack",  kcal: 539, p: 6,    c: 57,  f: 31, serving: { label: "1 tbsp (20 g)", grams: 20 } },
  { id: "ketchup",        name: "Ketchup",                  cat: "snack",   kcal: 101, p: 1.7,  c: 27,  f: 0.1, serving: { label: "1 tbsp (17 g)", grams: 17 } },
  { id: "dark-choc",      name: "Dark chocolate 70%",       cat: "snack",   kcal: 598, p: 7.8,  c: 46,  f: 43, serving: { label: "2 squares (25 g)", grams: 25 } },
  { id: "milk-choc",      name: "Milk chocolate",           cat: "snack",   kcal: 535, p: 7.6,  c: 59,  f: 30, serving: { label: "2 squares (25 g)", grams: 25 } },
  { id: "chips",          name: "Potato chips",             cat: "snack",   kcal: 536, p: 7,    c: 53,  f: 35, serving: { label: "small bag (28 g)", grams: 28 } },
  { id: "popcorn",        name: "Popcorn (air-popped)",     cat: "snack",   kcal: 387, p: 13,   c: 78,  f: 4.5, serving: { label: "1 portion (30 g)", grams: 30 } },
  { id: "pretzels",       name: "Pretzels",                 cat: "snack",   kcal: 384, p: 10,   c: 80,  f: 3,  serving: { label: "1 portion (30 g)", grams: 30 } },
  { id: "cookies",        name: "Cookies",                  cat: "snack",   kcal: 502, p: 5.5,  c: 64,  f: 25, serving: { label: "1 cookie (16 g)", grams: 16 } },
  { id: "granola-bar",    name: "Granola bar",              cat: "snack",   kcal: 471, p: 8,    c: 64,  f: 20, serving: { label: "1 bar (40 g)", grams: 40 } },
  { id: "donut",          name: "Donut",                    cat: "snack",   kcal: 452, p: 4.9,  c: 51,  f: 25, serving: { label: "1 donut (60 g)", grams: 60 } },
  { id: "muffin",         name: "Blueberry muffin",         cat: "snack",   kcal: 377, p: 5,    c: 55,  f: 15, serving: { label: "1 muffin (113 g)", grams: 113 } },
  { id: "croissant",      name: "Croissant",                cat: "snack",   kcal: 406, p: 8,    c: 46,  f: 21, serving: { label: "1 croissant (57 g)", grams: 57 } },
  { id: "ice-cream",      name: "Ice cream, vanilla",       cat: "snack",   kcal: 207, p: 3.5,  c: 24,  f: 11, serving: { label: "1 scoop (66 g)", grams: 66 } },
  { id: "pizza",          name: "Pizza, cheese",            cat: "snack",   kcal: 266, p: 11,   c: 33,  f: 10, serving: { label: "1 slice (107 g)", grams: 107 } },

  // ---- Drinks (per 100 ml) ----
  { id: "water",          name: "Water",                    cat: "drink",   kcal: 0,   p: 0,    c: 0,   f: 0,  serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "coffee-black",   name: "Coffee, black",            cat: "drink",   kcal: 1,   p: 0.1,  c: 0,   f: 0,  serving: { label: "1 cup (240 ml)", grams: 240 } },
  { id: "coffee-milk",    name: "Coffee w/ milk & sugar",   cat: "drink",   kcal: 30,  p: 1,    c: 4,   f: 1,  serving: { label: "1 cup (250 ml)", grams: 250 } },
  { id: "latte",          name: "Caffè latte",              cat: "drink",   kcal: 55,  p: 3,    c: 5,   f: 2,  serving: { label: "1 cup (240 ml)", grams: 240 } },
  { id: "cappuccino",     name: "Cappuccino",               cat: "drink",   kcal: 35,  p: 2,    c: 3,   f: 1.5, serving: { label: "1 cup (180 ml)", grams: 180 } },
  { id: "green-tea",      name: "Green tea (unsweetened)",  cat: "drink",   kcal: 1,   p: 0,    c: 0.2, f: 0,  serving: { label: "1 cup (240 ml)", grams: 240 } },
  { id: "black-tea",      name: "Black tea (unsweetened)",  cat: "drink",   kcal: 1,   p: 0,    c: 0.3, f: 0,  serving: { label: "1 cup (240 ml)", grams: 240 } },
  { id: "iced-tea",       name: "Iced tea (sweetened)",     cat: "drink",   kcal: 30,  p: 0,    c: 7.5, f: 0,  serving: { label: "1 can (330 ml)", grams: 330 } },
  { id: "hot-chocolate",  name: "Hot chocolate",            cat: "drink",   kcal: 77,  p: 3.5,  c: 11,  f: 2.3, serving: { label: "1 cup (240 ml)", grams: 240 } },
  { id: "whole-milk",     name: "Whole milk",               cat: "drink",   kcal: 61,  p: 3.2,  c: 4.8, f: 3.3, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "skim-milk",      name: "Skim milk",                cat: "drink",   kcal: 34,  p: 3.4,  c: 5,   f: 0.1, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "almond-milk",    name: "Almond milk, unsweetened", cat: "drink",   kcal: 15,  p: 0.5,  c: 0.6, f: 1.2, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "soy-milk",       name: "Soy milk",                 cat: "drink",   kcal: 43,  p: 3.3,  c: 1.8, f: 1.8, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "oat-milk",       name: "Oat milk",                 cat: "drink",   kcal: 47,  p: 1,    c: 7,   f: 1.5, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "protein-shake",  name: "Protein shake (in water)", cat: "drink",   kcal: 40,  p: 8,    c: 1,   f: 0.6, serving: { label: "1 shake (300 ml)", grams: 300 } },
  { id: "protein-shake-milk", name: "Protein shake (with milk)", cat: "drink", kcal: 75, p: 9,  c: 6,   f: 2.2, serving: { label: "1 shake (350 ml)", grams: 350 } },
  { id: "protein-smoothie", name: "Protein smoothie (fruit + whey)", cat: "drink", kcal: 64, p: 6, c: 9, f: 1,  serving: { label: "1 smoothie (400 ml)", grams: 400 } },
  { id: "mass-gainer",    name: "Mass gainer shake",        cat: "drink",   kcal: 170, p: 12,   c: 26,  f: 3,  serving: { label: "1 shake (400 ml)", grams: 400 } },
  { id: "chocolate-milk", name: "Chocolate milk",           cat: "drink",   kcal: 83,  p: 3.2,  c: 13,  f: 2.3, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "orange-juice",   name: "Orange juice",             cat: "drink",   kcal: 45,  p: 0.7,  c: 10,  f: 0.2, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "apple-juice",    name: "Apple juice",              cat: "drink",   kcal: 46,  p: 0.1,  c: 11,  f: 0.1, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "lemonade",       name: "Lemonade",                 cat: "drink",   kcal: 40,  p: 0,    c: 10,  f: 0,  serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "coconut-water",  name: "Coconut water",            cat: "drink",   kcal: 19,  p: 0.7,  c: 3.7, f: 0.2, serving: { label: "1 glass (250 ml)", grams: 250 } },
  { id: "cola",           name: "Cola",                     cat: "drink",   kcal: 42,  p: 0,    c: 11,  f: 0,  serving: { label: "1 can (330 ml)", grams: 330 } },
  { id: "diet-cola",      name: "Diet cola",                cat: "drink",   kcal: 0,   p: 0,    c: 0,   f: 0,  serving: { label: "1 can (330 ml)", grams: 330 } },
  { id: "sports-drink",   name: "Sports drink",             cat: "drink",   kcal: 25,  p: 0,    c: 6,   f: 0,  serving: { label: "1 bottle (500 ml)", grams: 500 } },
  { id: "energy-drink",   name: "Energy drink",             cat: "drink",   kcal: 45,  p: 0,    c: 11,  f: 0,  serving: { label: "1 can (250 ml)", grams: 250 } },
  { id: "beer",           name: "Beer (lager)",             cat: "drink",   kcal: 43,  p: 0.5,  c: 3.6, f: 0,  serving: { label: "1 bottle (330 ml)", grams: 330 } },
  { id: "wine-red",       name: "Wine, red",                cat: "drink",   kcal: 85,  p: 0.1,  c: 2.6, f: 0,  serving: { label: "1 glass (150 ml)", grams: 150 } },
  { id: "wine-white",     name: "Wine, white",              cat: "drink",   kcal: 82,  p: 0.1,  c: 2.6, f: 0,  serving: { label: "1 glass (150 ml)", grams: 150 } },
  { id: "champagne",      name: "Sparkling wine",           cat: "drink",   kcal: 81,  p: 0.2,  c: 1.4, f: 0,  serving: { label: "1 glass (120 ml)", grams: 120 } },
  { id: "spirits",        name: "Spirits (vodka/whiskey)",  cat: "drink",   kcal: 231, p: 0,    c: 0,   f: 0,  serving: { label: "1 shot (30 ml)", grams: 30 } },

  // ---- Meals & dishes (prepared / commonly eaten, per 100 g) ----
  { id: "breaded-chicken", name: "Breaded chicken breast (schnitzel)", cat: "meal", kcal: 250, p: 18, c: 14, f: 13, serving: { label: "1 fillet (150 g)", grams: 150 } },
  { id: "chicken-nuggets", name: "Chicken nuggets",          cat: "meal",    kcal: 296, p: 15,   c: 18,  f: 18, serving: { label: "6 nuggets (96 g)", grams: 96 } },
  { id: "chicken-tenders", name: "Breaded chicken tenders",  cat: "meal",    kcal: 263, p: 18,   c: 16,  f: 13, serving: { label: "1 tender (50 g)", grams: 50 } },
  { id: "popcorn-chicken", name: "Popcorn chicken",          cat: "meal",    kcal: 290, p: 16,   c: 19,  f: 17, serving: { label: "1 portion (114 g)", grams: 114 } },
  { id: "fried-chicken",  name: "Fried chicken (drumstick)", cat: "meal",    kcal: 260, p: 19,   c: 9,   f: 16, serving: { label: "1 piece (90 g)", grams: 90 } },
  { id: "chicken-wrap",   name: "Grilled chicken wrap",      cat: "meal",    kcal: 218, p: 13,   c: 22,  f: 8,  serving: { label: "1 wrap (250 g)", grams: 250 } },
  { id: "chicken-caesar", name: "Chicken Caesar salad",      cat: "meal",    kcal: 130, p: 9,    c: 5,   f: 8,  serving: { label: "1 bowl (250 g)", grams: 250 } },
  { id: "cheeseburger",   name: "Cheeseburger",              cat: "meal",    kcal: 268, p: 15,   c: 27,  f: 11, serving: { label: "1 burger (115 g)", grams: 115 } },
  { id: "hamburger",      name: "Hamburger",                 cat: "meal",    kcal: 254, p: 13,   c: 30,  f: 9,  serving: { label: "1 burger (110 g)", grams: 110 } },
  { id: "crispy-chicken-burger", name: "Crispy chicken burger", cat: "meal", kcal: 270, p: 14,   c: 27,  f: 12, serving: { label: "1 burger (180 g)", grams: 180 } },
  { id: "hot-dog",        name: "Hot dog (with bun)",        cat: "meal",    kcal: 290, p: 10,   c: 22,  f: 18, serving: { label: "1 hot dog (98 g)", grams: 98 } },
  { id: "pizza-pepperoni", name: "Pizza, pepperoni",         cat: "meal",    kcal: 280, p: 12,   c: 30,  f: 12, serving: { label: "1 slice (110 g)", grams: 110 } },
  { id: "spaghetti-bolognese", name: "Spaghetti bolognese",  cat: "meal",    kcal: 140, p: 8,    c: 16,  f: 5,  serving: { label: "1 plate (350 g)", grams: 350 } },
  { id: "lasagna",        name: "Lasagna",                   cat: "meal",    kcal: 135, p: 8,    c: 11,  f: 6,  serving: { label: "1 portion (250 g)", grams: 250 } },
  { id: "mac-cheese",     name: "Macaroni & cheese",         cat: "meal",    kcal: 164, p: 6,    c: 20,  f: 7,  serving: { label: "1 cup (200 g)", grams: 200 } },
  { id: "fried-rice",     name: "Fried rice",                cat: "meal",    kcal: 168, p: 5,    c: 22,  f: 6,  serving: { label: "1 cup (198 g)", grams: 198 } },
  { id: "burrito",        name: "Beef & bean burrito",       cat: "meal",    kcal: 206, p: 9,    c: 24,  f: 8,  serving: { label: "1 burrito (220 g)", grams: 220 } },
  { id: "beef-taco",      name: "Beef taco",                 cat: "meal",    kcal: 226, p: 9,    c: 20,  f: 12, serving: { label: "1 taco (80 g)", grams: 80 } },
  { id: "sushi-roll",     name: "Sushi roll (California)",   cat: "meal",    kcal: 145, p: 5,    c: 28,  f: 2,  serving: { label: "6 pieces (170 g)", grams: 170 } },
  { id: "grilled-cheese", name: "Grilled cheese sandwich",   cat: "meal",    kcal: 330, p: 12,   c: 28,  f: 19, serving: { label: "1 sandwich (120 g)", grams: 120 } },
  { id: "blt-sandwich",   name: "BLT sandwich",              cat: "meal",    kcal: 235, p: 9,    c: 23,  f: 12, serving: { label: "1 sandwich (180 g)", grams: 180 } },
  { id: "tuna-sandwich",  name: "Tuna mayo sandwich",        cat: "meal",    kcal: 230, p: 11,   c: 24,  f: 10, serving: { label: "1 sandwich (185 g)", grams: 185 } },
  { id: "club-sandwich",  name: "Club sandwich",             cat: "meal",    kcal: 233, p: 12,   c: 20,  f: 12, serving: { label: "1 sandwich (230 g)", grams: 230 } },
  { id: "chicken-curry",  name: "Chicken curry",             cat: "meal",    kcal: 130, p: 10,   c: 6,   f: 7,  serving: { label: "1 bowl (300 g)", grams: 300 } },
  { id: "pad-thai",       name: "Pad thai",                  cat: "meal",    kcal: 153, p: 7,    c: 20,  f: 5,  serving: { label: "1 plate (300 g)", grams: 300 } },
  { id: "doner-kebab",    name: "Doner kebab wrap",          cat: "meal",    kcal: 215, p: 12,   c: 18,  f: 11, serving: { label: "1 kebab (300 g)", grams: 300 } },
  { id: "fish-and-chips", name: "Fish & chips",              cat: "meal",    kcal: 230, p: 11,   c: 22,  f: 11, serving: { label: "1 portion (300 g)", grams: 300 } },
  { id: "breaded-fish",   name: "Breaded fish fillet",       cat: "meal",    kcal: 250, p: 12,   c: 18,  f: 13, serving: { label: "1 fillet (100 g)", grams: 100 } },
  { id: "fish-sticks",    name: "Fish sticks",               cat: "meal",    kcal: 249, p: 13,   c: 20,  f: 13, serving: { label: "1 stick (28 g)", grams: 28 } },
  { id: "meatballs",      name: "Meatballs (beef)",          cat: "meal",    kcal: 197, p: 14,   c: 6,   f: 13, serving: { label: "1 meatball (30 g)", grams: 30 } },
  { id: "cheese-omelette", name: "Cheese omelette",          cat: "meal",    kcal: 154, p: 11,   c: 1,   f: 12, serving: { label: "1 omelette (150 g)", grams: 150 } },
  { id: "scrambled-eggs", name: "Scrambled eggs",            cat: "meal",    kcal: 149, p: 10,   c: 1.6, f: 11, serving: { label: "2 eggs (110 g)", grams: 110 } },
  { id: "loaded-nachos",  name: "Loaded nachos",             cat: "meal",    kcal: 320, p: 8,    c: 32,  f: 18, serving: { label: "1 portion (150 g)", grams: 150 } },
  { id: "pork-dumplings", name: "Pork dumplings",            cat: "meal",    kcal: 220, p: 9,    c: 25,  f: 9,  serving: { label: "3 dumplings (90 g)", grams: 90 } },
  { id: "spring-roll",    name: "Spring roll",               cat: "meal",    kcal: 220, p: 5,    c: 25,  f: 11, serving: { label: "1 roll (60 g)", grams: 60 } },
];

/* ----------------------------------------------------------------------------
   Cardio activities with MET values (Metabolic Equivalent of Task).
   Calories burned = MET × 3.5 × bodyWeightKg / 200 × minutes.
   -------------------------------------------------------------------------- */
const CARDIO_ACTIVITIES = [
  { id: "walk-slow",     name: "Walking (5 km/h)",            met: 3.5 },
  { id: "walk-brisk",    name: "Walking, brisk (6.5 km/h)",   met: 5.0 },
  { id: "hiking",        name: "Hiking",                       met: 6.0 },
  { id: "run-8",         name: "Running (8 km/h)",            met: 8.3 },
  { id: "run-10",        name: "Running (10 km/h)",           met: 9.8 },
  { id: "run-12",        name: "Running (12 km/h)",           met: 11.8 },
  { id: "run-15",        name: "Running (15 km/h)",           met: 14.5 },
  { id: "cycle-easy",    name: "Cycling, leisure (<16 km/h)", met: 4.0 },
  { id: "cycle-mod",     name: "Cycling, moderate (19–22 km/h)", met: 8.0 },
  { id: "cycle-hard",    name: "Cycling, vigorous (>22 km/h)", met: 10.0 },
  { id: "bike-stationary", name: "Stationary bike, moderate", met: 7.0 },
  { id: "swim-easy",     name: "Swimming, leisure",           met: 6.0 },
  { id: "swim-laps",     name: "Swimming laps, vigorous",     met: 9.8 },
  { id: "row-mod",       name: "Rowing machine, moderate",    met: 7.0 },
  { id: "row-hard",      name: "Rowing machine, vigorous",    met: 8.5 },
  { id: "elliptical",    name: "Elliptical trainer",          met: 5.0 },
  { id: "stairs",        name: "Stair climber",               met: 9.0 },
  { id: "jump-rope",     name: "Jump rope",                   met: 12.3 },
  { id: "hiit",          name: "HIIT / circuit training",     met: 8.0 },
  { id: "boxing-bag",    name: "Boxing (heavy bag)",          met: 7.8 },
  { id: "dancing",       name: "Dancing",                     met: 5.0 },
  { id: "basketball",    name: "Basketball",                  met: 6.5 },
  { id: "soccer",        name: "Soccer",                      met: 7.0 },
  { id: "tennis",        name: "Tennis",                      met: 7.3 },
  { id: "yoga",          name: "Yoga",                        met: 2.5 },
];

/* ----------------------------------------------------------------------------
   Exercise library grouped by muscle, and tagged by equipment so the picker
   can differentiate Barbell / Dumbbell / Machine / Cable / Bodyweight options.
   -------------------------------------------------------------------------- */
const SEED_EXERCISES = [
  // ---- Chest ----
  { id: "bench-press",       name: "Barbell Bench Press",        muscle: "Chest", equip: "Barbell" },
  { id: "incline-bench-press", name: "Incline Barbell Bench Press", muscle: "Chest", equip: "Barbell" },
  { id: "decline-bench",     name: "Decline Barbell Press",      muscle: "Chest", equip: "Barbell" },
  { id: "db-bench-press",    name: "Dumbbell Bench Press",       muscle: "Chest", equip: "Dumbbell" },
  { id: "incline-db-press",  name: "Incline Dumbbell Press",     muscle: "Chest", equip: "Dumbbell" },
  { id: "db-fly",            name: "Dumbbell Fly",               muscle: "Chest", equip: "Dumbbell" },
  { id: "machine-chest",     name: "Machine Chest Press",        muscle: "Chest", equip: "Machine" },
  { id: "pec-deck",          name: "Pec Deck Machine",           muscle: "Chest", equip: "Machine" },
  { id: "cable-crossover",   name: "Cable Crossover",            muscle: "Chest", equip: "Cable" },
  { id: "pushup",            name: "Push-up",                    muscle: "Chest", equip: "Bodyweight" },
  { id: "chest-dip",         name: "Chest Dip",                  muscle: "Chest", equip: "Bodyweight" },

  // ---- Back ----
  { id: "deadlift",          name: "Deadlift",                   muscle: "Back", equip: "Barbell" },
  { id: "barbell-row",       name: "Barbell Row",                muscle: "Back", equip: "Barbell" },
  { id: "pendlay-row",       name: "Pendlay Row",                muscle: "Back", equip: "Barbell" },
  { id: "tbar-row",          name: "T-Bar Row",                  muscle: "Back", equip: "Barbell" },
  { id: "db-row",            name: "Dumbbell Row",               muscle: "Back", equip: "Dumbbell" },
  { id: "chest-supported-row", name: "Chest-Supported DB Row",   muscle: "Back", equip: "Dumbbell" },
  { id: "lat-pulldown",      name: "Lat Pulldown",               muscle: "Back", equip: "Machine" },
  { id: "machine-row",       name: "Machine Row",                muscle: "Back", equip: "Machine" },
  { id: "seated-row",        name: "Seated Cable Row",           muscle: "Back", equip: "Cable" },
  { id: "cable-pullover",    name: "Cable Pullover",             muscle: "Back", equip: "Cable" },
  { id: "face-pull",         name: "Face Pull",                  muscle: "Back", equip: "Cable" },
  { id: "pullup",            name: "Pull-up",                    muscle: "Back", equip: "Bodyweight" },
  { id: "chinup",            name: "Chin-up",                    muscle: "Back", equip: "Bodyweight" },

  // ---- Shoulders ----
  { id: "ohp",               name: "Overhead Press",             muscle: "Shoulders", equip: "Barbell" },
  { id: "push-press",        name: "Push Press",                 muscle: "Shoulders", equip: "Barbell" },
  { id: "upright-row",       name: "Barbell Upright Row",        muscle: "Shoulders", equip: "Barbell" },
  { id: "db-shoulder",       name: "Dumbbell Shoulder Press",    muscle: "Shoulders", equip: "Dumbbell" },
  { id: "arnold-press",      name: "Arnold Press",               muscle: "Shoulders", equip: "Dumbbell" },
  { id: "lateral-raise",     name: "Dumbbell Lateral Raise",     muscle: "Shoulders", equip: "Dumbbell" },
  { id: "front-raise",       name: "Dumbbell Front Raise",       muscle: "Shoulders", equip: "Dumbbell" },
  { id: "rear-delt-fly",     name: "Rear Delt Dumbbell Fly",     muscle: "Shoulders", equip: "Dumbbell" },
  { id: "machine-shoulder-press", name: "Machine Shoulder Press", muscle: "Shoulders", equip: "Machine" },
  { id: "reverse-pec-deck",  name: "Reverse Pec Deck",           muscle: "Shoulders", equip: "Machine" },
  { id: "cable-lateral",     name: "Cable Lateral Raise",        muscle: "Shoulders", equip: "Cable" },

  // ---- Legs ----
  { id: "back-squat",        name: "Back Squat",                 muscle: "Legs", equip: "Barbell" },
  { id: "front-squat",       name: "Front Squat",                muscle: "Legs", equip: "Barbell" },
  { id: "rdl",               name: "Romanian Deadlift",          muscle: "Legs", equip: "Barbell" },
  { id: "hip-thrust",        name: "Barbell Hip Thrust",         muscle: "Legs", equip: "Barbell" },
  { id: "barbell-lunge",     name: "Barbell Lunge",              muscle: "Legs", equip: "Barbell" },
  { id: "goblet-squat",      name: "Goblet Squat",               muscle: "Legs", equip: "Dumbbell" },
  { id: "lunge",             name: "Dumbbell Lunge",             muscle: "Legs", equip: "Dumbbell" },
  { id: "bulgarian-split",   name: "Bulgarian Split Squat",      muscle: "Legs", equip: "Dumbbell" },
  { id: "db-rdl",            name: "Dumbbell Romanian Deadlift", muscle: "Legs", equip: "Dumbbell" },
  { id: "leg-press",         name: "Leg Press",                  muscle: "Legs", equip: "Machine" },
  { id: "hack-squat",        name: "Hack Squat",                 muscle: "Legs", equip: "Machine" },
  { id: "leg-extension",     name: "Leg Extension",              muscle: "Legs", equip: "Machine" },
  { id: "leg-curl",          name: "Leg Curl",                   muscle: "Legs", equip: "Machine" },
  { id: "calf-raise",        name: "Standing Calf Raise",        muscle: "Legs", equip: "Machine" },
  { id: "seated-calf",       name: "Seated Calf Raise",          muscle: "Legs", equip: "Machine" },
  { id: "walking-lunge",     name: "Walking Lunge",              muscle: "Legs", equip: "Bodyweight" },

  // ---- Biceps ----
  { id: "barbell-curl",      name: "Barbell Curl",               muscle: "Biceps", equip: "Barbell" },
  { id: "ez-bar-curl",       name: "EZ-Bar Curl",                muscle: "Biceps", equip: "Barbell" },
  { id: "db-curl",           name: "Dumbbell Curl",              muscle: "Biceps", equip: "Dumbbell" },
  { id: "hammer-curl",       name: "Hammer Curl",                muscle: "Biceps", equip: "Dumbbell" },
  { id: "incline-db-curl",   name: "Incline Dumbbell Curl",      muscle: "Biceps", equip: "Dumbbell" },
  { id: "concentration-curl", name: "Concentration Curl",        muscle: "Biceps", equip: "Dumbbell" },
  { id: "preacher-curl",     name: "Preacher Curl",              muscle: "Biceps", equip: "Machine" },
  { id: "cable-curl",        name: "Cable Curl",                 muscle: "Biceps", equip: "Cable" },

  // ---- Triceps ----
  { id: "cgbp",              name: "Close-Grip Bench Press",     muscle: "Triceps", equip: "Barbell" },
  { id: "skullcrusher",      name: "Skullcrusher",               muscle: "Triceps", equip: "Barbell" },
  { id: "overhead-tricep",   name: "Dumbbell Overhead Extension", muscle: "Triceps", equip: "Dumbbell" },
  { id: "db-kickback",       name: "Dumbbell Kickback",          muscle: "Triceps", equip: "Dumbbell" },
  { id: "machine-tricep",    name: "Machine Tricep Extension",   muscle: "Triceps", equip: "Machine" },
  { id: "tricep-pushdown",   name: "Tricep Pushdown",            muscle: "Triceps", equip: "Cable" },
  { id: "cable-overhead-tricep", name: "Cable Overhead Extension", muscle: "Triceps", equip: "Cable" },
  { id: "tricep-dip",        name: "Tricep Dip",                 muscle: "Triceps", equip: "Bodyweight" },

  // ---- Core ----
  { id: "cable-crunch",      name: "Cable Crunch",               muscle: "Core", equip: "Cable" },
  { id: "machine-crunch",    name: "Machine Crunch",             muscle: "Core", equip: "Machine" },
  { id: "plank",             name: "Plank",                      muscle: "Core", equip: "Bodyweight" },
  { id: "crunch",            name: "Crunch",                     muscle: "Core", equip: "Bodyweight" },
  { id: "hanging-leg-raise", name: "Hanging Leg Raise",          muscle: "Core", equip: "Bodyweight" },
  { id: "russian-twist",     name: "Russian Twist",              muscle: "Core", equip: "Bodyweight" },
  { id: "ab-wheel",          name: "Ab Wheel",                   muscle: "Core", equip: "Bodyweight" },
];

/* ----------------------------------------------------------------------------
   Predefined workout splits. Each split has named days, and each day lists
   default exercises (by exercise id) that get prefilled when you log it.
   -------------------------------------------------------------------------- */
const SEED_SPLITS = [
  {
    id: "ppl",
    name: "Push / Pull / Legs",
    builtIn: true,
    days: [
      { name: "Push", exercises: ["bench-press", "incline-db-press", "ohp", "lateral-raise", "tricep-pushdown", "overhead-tricep"] },
      { name: "Pull", exercises: ["deadlift", "pullup", "barbell-row", "lat-pulldown", "face-pull", "barbell-curl", "hammer-curl"] },
      { name: "Legs", exercises: ["back-squat", "rdl", "leg-press", "leg-curl", "calf-raise"] },
    ],
  },
  {
    id: "upper-lower",
    name: "Upper / Lower",
    builtIn: true,
    days: [
      { name: "Upper", exercises: ["bench-press", "barbell-row", "ohp", "lat-pulldown", "barbell-curl", "tricep-pushdown"] },
      { name: "Lower", exercises: ["back-squat", "rdl", "leg-press", "leg-curl", "calf-raise", "plank"] },
    ],
  },
  {
    id: "full-body",
    name: "Full Body (3-day)",
    builtIn: true,
    days: [
      { name: "Full Body A", exercises: ["back-squat", "bench-press", "barbell-row", "ohp", "plank"] },
      { name: "Full Body B", exercises: ["deadlift", "incline-db-press", "pullup", "lunge", "lateral-raise"] },
      { name: "Full Body C", exercises: ["front-squat", "machine-chest", "seated-row", "db-shoulder", "hanging-leg-raise"] },
    ],
  },
  {
    id: "bro-split",
    name: "Bro Split (5-day)",
    builtIn: true,
    days: [
      { name: "Chest", exercises: ["bench-press", "incline-db-press", "db-fly", "cable-crossover", "chest-dip"] },
      { name: "Back", exercises: ["deadlift", "pullup", "barbell-row", "lat-pulldown", "seated-row"] },
      { name: "Shoulders", exercises: ["ohp", "lateral-raise", "front-raise", "rear-delt-fly", "upright-row"] },
      { name: "Legs", exercises: ["back-squat", "leg-press", "rdl", "leg-curl", "calf-raise"] },
      { name: "Arms", exercises: ["barbell-curl", "hammer-curl", "preacher-curl", "tricep-pushdown", "skullcrusher"] },
    ],
  },
  {
    id: "arnold",
    name: "Arnold Split (6-day)",
    builtIn: true,
    days: [
      { name: "Chest & Back", exercises: ["bench-press", "incline-db-press", "barbell-row", "pullup", "db-fly"] },
      { name: "Shoulders & Arms", exercises: ["ohp", "lateral-raise", "barbell-curl", "tricep-pushdown", "hammer-curl", "skullcrusher"] },
      { name: "Legs", exercises: ["back-squat", "rdl", "leg-press", "leg-curl", "calf-raise"] },
    ],
  },
];

/* Sensible default daily goals (the user edits these in the app). */
const DEFAULT_GOALS = { calories: 2200, protein: 150, carbs: 220, fat: 70 };
